version: '3.9'

services:
  node:
    image: node
    #    build:
    #      context: ./bknprocessing
    #      dockerfile: node.Dockerfile
    container_name: node
    ports:
      - "8080:8080"
    networks: [ bknprocessing ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks: [ bknprocessing ]
    depends_on:
      - node
    volumes:
      - ./configuration/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: bknprocessing_grafana
    restart: always
    image: grafana/grafana
    ports:
      - "8000:3000"
    networks: [ bknprocessing ]

networks:
  bknprocessing:
    name: bknprocessing

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1